[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[package]
name = "qanvuli"
edition.workspace = true
version.workspace = true
license.workspace = true

[features]
default = ["enrichment", "mcp", "tui"]
enrichment = [
    "qanvuli-app-commands/enrichment",
    "qanvuli-app-mcp?/enrichment",
    "qanvuli-app-tui?/enrichment",
]
mcp = ["dep:qanvuli-app-mcp"]
tui = ["dep:qanvuli-app-tui"]

[[bin]]
name = "qanvuli"
path = "app/src/main.rs"

[dependencies]
qanvuli-app-commands = { version = "*", path = "app/crates/commands", default-features = false }
qanvuli-app-mcp = { version = "*", path = "app/crates/mcp", default-features = false, optional = true }
qanvuli-app-tui = { version = "*", path = "app/crates/tui", default-features = false, optional = true }
qanvuli-utils = { version = "*", path = "utils" }
clap = { version = "4.6", features = ["derive"] }
tokio = { version = "1.52", features = ["io-std", "macros", "rt", "sync"] }


[workspace]
default-members = ["."]
members = [
    "app/crates/commands",
    "app/crates/mcp",
    "app/crates/tui",
    "collector",
    "core",
    "db",
    "models",
    "utils",
]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
strip = true
panic = 'abort'
incremental = false
overflow-checks = false
