[workspace.package]
edition = "2024"
version = "0.1.0"


[workspace]
members = ["collector", "core", "db", "models", "test", "utils"]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
strip = true
panic = 'abort'
incremental = false
overflow-checks = false
