//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cve")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub cve_id: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text")]
    pub published_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    pub serial: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description_en: Option<String>,
    pub cvss_score: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cvss_severity: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cvss_vector: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub products_json: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub vendors_json: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cwe_id_description_json: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub raw_json: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
