//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cve")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub cve_id: String,
    #[sea_orm(column_type = "Text")]
    pub state: String,
    #[sea_orm(column_type = "Text")]
    pub published_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    pub serial: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description_en: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub raw_json: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cve_affected::Entity")]
    CveAffected,
    #[sea_orm(has_many = "super::cve_cvss::Entity")]
    CveCvss,
    #[sea_orm(has_many = "super::cve_cwe::Entity")]
    CveCwe,
}

impl Related<super::cve_affected::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CveAffected.def()
    }
}

impl Related<super::cve_cvss::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CveCvss.def()
    }
}

impl Related<super::cve_cwe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CveCwe.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
