//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cve_cwe")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub cve_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub cwe_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cve::Entity",
        from = "Column::CveId",
        to = "super::cve::Column::CveId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cve,
}

impl Related<super::cve::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cve.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
