//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cve_affected")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cve_db_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub vendor: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub product: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub package_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub collection_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub default_status: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub raw_json: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cve::Entity",
        from = "Column::CveDbId",
        to = "super::cve::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cve,
}

impl Related<super::cve::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cve.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
