//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cve_cwe")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cve_db_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub cwe_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cve::Entity",
        from = "Column::CveDbId",
        to = "super::cve::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cve,
    #[sea_orm(
        belongs_to = "super::cwe::Entity",
        from = "Column::CweId",
        to = "super::cwe::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cwe,
}

impl Related<super::cve::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cve.def()
    }
}

impl Related<super::cwe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cwe.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
