//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cve_cvss")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub cve_id: String,
    #[sea_orm(column_type = "Text")]
    pub version: String,
    pub base_score: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub base_severity: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub vector_string: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub source: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub raw_json: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cve::Entity",
        from = "Column::CveId",
        to = "super::cve::Column::CveId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Cve,
}

impl Related<super::cve::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cve.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
