//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod app_metadata;
pub mod cve;
pub mod cve_affected;
pub mod cve_cvss;
pub mod cve_cwe;
pub mod cve_zip_file;
pub mod cwe;
pub mod read_json_file;
