[package]
name = "qanvuli-app-tui"
edition.workspace = true
version.workspace = true

[dependencies]
qanvuli-app-commands = { version = "*", path = "../commands" }
qanvuli-db = { version = "*", path = "../../../db" }
chrono = "0.4"
clap = { version = "4.6", features = ["derive"] }
crossterm = "0.29"
ratatui = "0.30"
regex = "1.12"
serde_json = "1"
tokio = { version = "1.52", features = ["rt", "sync"] }
