[package]
name = "qanvuli-app"
edition.workspace = true
version.workspace = true

[dependencies]
qanvuli-app-commands = { version = "*", path = "crates/commands" }
qanvuli-app-mcp = { version = "*", path = "crates/mcp" }
qanvuli-app-tui = { version = "*", path = "crates/tui" }
qanvuli-utils = { version = "*", path = "../utils" }
clap = { version = "4.6", features = ["derive"] }
tokio = { version = "1.52", features = ["io-std", "macros", "rt", "sync"] }
