[package]
name = "qanvuli-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.100"
chrono = { version = "0.4.42", features = ["serde"] }
once_cell = "1.21.3"
serde = { version = "1.0.228", features = ["derive", "serde_derive"] }
serde_json = "1.0.145"
serde_valid = { version = "2.0.0", features = ["toml"] }
simd-json = { version = "0.17.0", features = ["ahash"] }
strum = { version = "0.28", features = ["derive"] }
thiserror = "2.0.17"
toml = { version = "1.1", features = ["fast_hash"] }

qanvuli-models = { version = "*", path = "../qanvuli-models" }
qanvuli-utils = { version = "*", path = "../qanvuli-utils" }
qanvuli-db = { version = "*", path = "../qanvuli-db" }

[lib]
doctest = false
