[package]
name = "qanvuli-collector"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
reqwest = { version = "0.13", features = [
    "rustls-no-provider",
    "stream",
], default-features = false }
qanvuli-utils = { version = "*", path = "../utils" }
